spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/cc_bmad_opus_certificate_management?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: CertificateHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.example.certificate: INFO
    org.springframework: WARN
  file:
    name: /var/log/certificate-management/app.log
    max-size: 50MB
    max-history: 30

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false