spring:
  application:
    name: certificate-management
  profiles:
    active: dev
    
server:
  port: 8080
  servlet:
    context-path: /api
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    root: INFO
    com.example.certificate: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/certificate-management.log
    max-size: 10MB
    max-history: 30