spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://prod-db-server:3306/certificate_management?useSSL=true&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}
      
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.certificate.domain.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      
logging:
  level:
    root: WARN
    com.example.certificate: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/certificate-management/app.log
    max-size: 50MB
    max-history: 90